# Generated by Django 4.1.6 on 2023-03-19 02:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Model',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("view_time", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sports", "Sports"),
                            ("entertainment", "Entertainment"),
                            ("misc", "Misc"),
                        ],
                        default="misc",
                        max_length=20,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, editable=False
                    ),
                ),
                (
                    "result_reveal_time",
                    models.DateTimeField(
                        default=posts.models.resut_reveal_time_function
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "viewed_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts_viewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Options_Model',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("AED9E0", "AED9E0"),
                            ("8CB369", "8CB369"),
                            ("D7A5E4", "D7A5E4"),
                            ("5D6DD3", "5D6DD3"),
                        ],
                        default="c1",
                        max_length=6,
                    ),
                ),
                (
                    "chosen_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_option",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.post_model",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.CharField(max_length=500)),
                (
                    "commented_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.post_model",
                    ),
                ),
            ],
        ),
    ]
