# Generated by Django 4.1.6 on 2023-03-15 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="options_model",
            name="chosen_by",
            field=models.ManyToManyField(
                blank=True, related_name="user_option", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="options_model",
            name="color",
            field=models.CharField(
                choices=[
                    ("aed9e0", "aed9e0"),
                    ("8cb369", "8cb369"),
                    ("D7A5E4", "D7A5E4"),
                    ("D7A5E4", "D7A5E4"),
                ],
                default="c1",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="post_model",
            name="category",
            field=models.CharField(
                choices=[
                    ("sports", "Sports"),
                    ("entertainment", "Entertainment"),
                    ("misc", "Misc"),
                ],
                default="misc",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post_model",
            name="viewed_by",
            field=models.ManyToManyField(
                blank=True, related_name="posts_viewed", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Comments_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.CharField(max_length=500)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.post_model",
                    ),
                ),
            ],
        ),
    ]
