# Generated by Django 4.1.6 on 2023-03-20 03:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_model",
            name="category",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("misc", "Misc"), ("sports", "Sports")],
                default="misc",
                max_length=20,
            ),
        ),
    ]
