# Generated by Django 4.1.6 on 2023-03-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="options_model",
            name="color",
            field=models.CharField(
                choices=[
                    ("AED9E0", "AED9E0"),
                    ("8CB369", "8CB369"),
                    ("D7A5E4", "D7A5E4"),
                    ("5D6DD3", "5D6DD3"),
                ],
                default="AED9E0",
                max_length=6,
            ),
        ),
    ]
