# Generated by Django 4.1.6 on 2023-03-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
