# Generated by Django 4.1.6 on 2023-03-18 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_model_created_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post_model",
            name="created_time",
        ),
    ]
