# Generated by Django 4.1.6 on 2023-03-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_comments_model_reported_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments_model",
            name="reported_count",
            field=models.IntegerField(default=0),
        ),
    ]
