# Generated by Django 4.1.6 on 2023-03-21 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_options_model_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpostviewtime",
            name="post",
        ),
        migrations.AddField(
            model_name="userpostviewtime",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.post_model",
            ),
            preserve_default=False,
        ),
    ]
