# Generated by Django 4.1.6 on 2023-03-08 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_post_model_viewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='options_model',
            name='chosen_by',
            field=models.ManyToManyField(blank=True, related_name='user_option', to=settings.AUTH_USER_MODEL),
        ),
    ]
