# Generated by Django 4.1.6 on 2023-03-18 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_remove_post_model_created_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="post_model",
            name="created_time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, editable=False
            ),
        ),
    ]
