# Generated by Django 4.1.6 on 2023-03-21 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_remove_userpostviewtime_post_userpostviewtime_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments_model",
            name="commented_time",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
