# Generated by Django 4.1.6 on 2023-03-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_comments_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="options_model",
            name="color",
            field=models.CharField(
                choices=[
                    ("c1", "aed9e0"),
                    ("c2", "8cb369"),
                    ("c3", "D7A5E4"),
                    ("c4", "D7A5E4"),
                ],
                default="c1",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="post_model",
            name="category",
            field=models.CharField(
                choices=[
                    ("sports", "Sports"),
                    ("entertainment", "Entertainment"),
                    ("misc", "Misc"),
                ],
                default="misc",
                max_length=20,
            ),
        ),
    ]
