# Generated by Django 4.1.6 on 2023-03-20 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_options_model_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post_model",
            name="view_time",
        ),
    ]
