# Generated by Django 4.1.6 on 2023-03-20 00:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0004_post_model_created_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post_model",
            name="view_time",
        ),
        migrations.CreateModel(
            name="UserPostViewTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_time",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("post", models.ManyToManyField(to="posts.post_model")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts_view_time",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
