# Generated by Django 4.1.6 on 2023-04-04 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0005_alter_comments_model_reported_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="post_model",
            name="reported_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="reported_post_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post_model",
            name="reported_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comments_model",
            name="reported_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="reported_comment_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
