# Generated by Django 4.1.6 on 2023-03-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_options_model_color_post_model_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="options_model",
            name="color",
            field=models.CharField(
                choices=[
                    ("aed9e0", "aed9e0"),
                    ("8cb369", "8cb369"),
                    ("D7A5E4", "D7A5E4"),
                    ("D7A5E4", "D7A5E4"),
                ],
                default="c1",
                max_length=6,
            ),
        ),
    ]
