# Generated by Django 4.1.6 on 2023-03-14 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0006_alter_options_model_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments_model",
            name="commented_by",
            field=models.ForeignKey(
                default="test",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
