# Generated by Django 4.1.6 on 2023-04-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_alter_post_model_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments_model",
            name="option_voted",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_option_voted",
                to="posts.options_model",
            ),
        ),
    ]
