# Generated by Django 4.1.6 on 2023-03-15 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_comments_model_commented_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments_model",
            name="commented_by",
        ),
    ]
