# Generated by Django 4.1.6 on 2023-03-15 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_options_model_chosen_by_options_model_color_and_more"),
        ("posts", "0008_remove_comments_model_commented_by"),
    ]

    operations = []
