# Generated by Django 4.1.6 on 2023-04-17 21:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0009_notification_model"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notification_Model",
            new_name="Noti_Model",
        ),
    ]
