# Generated by Django 4.1.6 on 2023-03-15 00:43

import datetime
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_comments_model_commented_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="post_model",
            name="created_time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="post_model",
            name="result_reveal_time",
            field=models.DateTimeField(default=posts.models.resut_reveal_time_function),
        ),
        migrations.AlterField(
            model_name="options_model",
            name="color",
            field=models.CharField(
                choices=[
                    ("AED9E0", "AED9E0"),
                    ("8CB369", "8CB369"),
                    ("D7A5E4", "D7A5E4"),
                    ("5D6DD3", "5D6DD3"),
                ],
                default="c1",
                max_length=6,
            ),
        ),
    ]
