# Generated by Django 4.1.6 on 2023-04-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_remove_noti_model_content_noti_model_noti_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="noti_model",
            name="comment_at",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.comments_model",
            ),
        ),
    ]
