# Generated by Django 4.1.6 on 2023-03-15 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_post_model_created_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post_model",
            name="view_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
