# Generated by Django 4.1.6 on 2023-04-17 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_noti_model_comment_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noti_model",
            name="comment_at",
        ),
    ]
