# Generated by Django 4.1.6 on 2023-04-17 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0013_remove_noti_model_comment_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noti_model",
            name="created_at",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
