# Generated by Django 4.1.6 on 2023-05-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_noti_model_content_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noti_model",
            name="content_text",
        ),
        migrations.AddField(
            model_name="noti_model",
            name="related_comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_noti_comment",
                to="posts.comments_model",
            ),
        ),
    ]
