# Generated by Django 4.1.6 on 2023-04-02 19:42

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custom_user",
            name="profile_picture",
            field=models.ImageField(
                default="default-profile.jpeg",
                upload_to="Profile-Pictures/",
                validators=[login.models.validate_image_extension],
            ),
        ),
    ]
