# Generated by Django 4.1.6 on 2023-05-08 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_custom_user_has_unread_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custom_user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w]+$",
                        "Enter a valid username. This value may contain only letters, numbers and _ characters.",
                        "invalid",
                    )
                ],
                verbose_name="username",
            ),
        ),
    ]
