# Generated by Django 4.1.6 on 2023-04-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection_model",
            name="connection_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accept"),
                    ("Declined", "Decline"),
                    ("Blocked", "Block"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
