# Generated by Django 4.1.6 on 2023-04-11 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_alter_connection_model_connection_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection_model",
            name="blocked_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
