# Generated by Django 4.1.6 on 2023-04-18 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_connection_model_blocked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat_message",
            name="seen_by",
            field=models.ManyToManyField(
                related_name="messages_seen", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="connection_model",
            name="latest_message",
            field=models.CharField(blank=True, max_length=23),
        ),
        migrations.AddField(
            model_name="connection_model",
            name="latest_message_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
