# Generated by Django 4.1.6 on 2023-04-18 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_chat_message_seen_by_connection_model_latest_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection_model",
            name="blocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
