# Generated by Django 4.1.6 on 2023-04-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_alter_connection_model_blocked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connection_model",
            name="latest_message",
        ),
        migrations.AlterField(
            model_name="chat_history",
            name="connection",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="get_chat_history",
                to="chat.connection_model",
            ),
        ),
    ]
